apiVersion: apps/v1
kind: Deployment
metadata: 
  name: carpeta-ciudadana-deployment
  labels: 
    app: node
spec: 
  replicas: 3
  selector : 
    matchLabels: 
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: carpeta-ciudadana
        image: sebospc/carpeta-ciudadana-backend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: carpeta-ciudadana-service
spec:
  type: LoadBalancer
  selector:
    app: node
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30163